// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYw1fm5XtH5o2OnBpL-mn2TEzpLYaylGk',
    appId: '1:838930331802:web:a181abd38d7f5ec30e0723',
    messagingSenderId: '838930331802',
    projectId: 'quran-app-de263',
    authDomain: 'quran-app-de263.firebaseapp.com',
    storageBucket: 'quran-app-de263.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYw1fm5XtH5o2OnBpL-mn2TEzpLYaylGk',
    appId: '1:838930331802:android:3d5cf244c1b5bb540e0723',
    messagingSenderId: '838930331802',
    projectId: 'quran-app-de263',
    storageBucket: 'quran-app-de263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4H_oR2inEJDh3-_bjgul9GmyAMASjN54',
    appId: '1:838930331802:ios:10b58706eeb7444c0e0723',
    messagingSenderId: '838930331802',
    projectId: 'quran-app-de263',
    storageBucket: 'quran-app-de263.firebasestorage.app',
    iosBundleId: 'com.quran.app',
  );
}
